## This file generated by InlineX::C2XS (version 0.24) using Inline::C (version 0.62_13)
package Math::MPFR::Prec;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

our $VERSION = '3.23';
$VERSION = eval $VERSION;
DynaLoader::bootstrap Math::MPFR::Prec $VERSION;

@Math::MPFR::Prec::EXPORT = ();
@Math::MPFR::Prec::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
