## This file generated by InlineX::C2XS (version 0.22) using Inline::C (version 0.5301)
package Math::MPFR::Prec;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Math::MPFR::Prec::VERSION = '3.22';

DynaLoader::bootstrap Math::MPFR::Prec $Math::MPFR::Prec::VERSION;

@Math::MPFR::Prec::EXPORT = ();
@Math::MPFR::Prec::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
